import 'package:flutter/material.dart';

import '../../../core/design/app_design_system.dart';
import 'report_definition.dart';

final List<ReportDefinition> reportDefinitions =
    List<ReportDefinition>.unmodifiable([
  ReportDefinition(
    id: 'salesInvoices',
    title: 'تقرير فواتير المبيعات',
    icon: Icons.point_of_sale_rounded,
    palette: AppModulePalettes.sales,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'فواتير المبيعات',
        icon: Icons.receipt_long_rounded,
        filters: _salesFilters,
        metrics: _salesMetrics,
        columns: _salesColumns,
        rows: _salesRows,
      ),
    ],
  ),
  ReportDefinition(
    id: 'purchaseInvoices',
    title: 'تقرير فواتير المشتريات',
    icon: Icons.shopping_cart_rounded,
    palette: AppModulePalettes.purchases,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'فواتير المشتريات',
        icon: Icons.receipt_long_rounded,
        filters: _purchaseFilters,
        metrics: _purchaseMetrics,
        columns: _purchaseColumns,
        rows: _purchaseRows,
      ),
    ],
  ),
  ReportDefinition(
    id: 'profits',
    title: 'تقرير الأرباح',
    icon: Icons.trending_up_rounded,
    palette: AppModulePalettes.company,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'الأرباح',
        icon: Icons.query_stats_rounded,
        filters: _profitFilters,
        metrics: _profitMetrics,
        columns: _profitColumns,
        rows: _profitRows,
        minimumColumnWidth: 145,
      ),
    ],
  ),
  ReportDefinition(
    id: 'inventory',
    title: 'تقرير المخزون والحركة المخزنية',
    icon: Icons.warehouse_rounded,
    palette: AppModulePalettes.warehouses,
    variants: [
      ReportVariantDefinition(
        id: 'currentStock',
        label: 'الرصيد الحالي',
        icon: Icons.inventory_2_rounded,
        filters: _currentStockFilters,
        metrics: _currentStockMetrics,
        columns: _currentStockColumns,
        rows: _currentStockRows,
      ),
      ReportVariantDefinition(
        id: 'transfers',
        label: 'سجل النقل المخزني',
        icon: Icons.swap_horiz_rounded,
        filters: _transferFilters,
        metrics: _transferMetrics,
        columns: _transferColumns,
        rows: _transferRows,
        minimumColumnWidth: 170,
      ),
    ],
  ),
  ReportDefinition(
    id: 'cashbox',
    title: 'تقرير الصندوق',
    icon: Icons.account_balance_wallet_rounded,
    palette: AppModulePalettes.cashbox,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'حركات الصندوق',
        icon: Icons.payments_rounded,
        filters: _cashboxFilters,
        metrics: _cashboxMetrics,
        columns: _cashboxColumns,
        rows: _cashboxRows,
      ),
    ],
  ),
  ReportDefinition(
    id: 'partyBalances',
    title: 'تقرير أرصدة الزبائن والمجهزين',
    icon: Icons.groups_rounded,
    palette: AppModulePalettes.parties,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'أرصدة الزبائن والمجهزين',
        icon: Icons.account_balance_rounded,
        filters: _partyBalanceFilters,
        metrics: _partyBalanceMetrics,
        columns: _partyBalanceColumns,
        rows: _partyBalanceRows,
      ),
    ],
  ),
  ReportDefinition(
    id: 'debtsInstallments',
    title: 'تقرير الديون والأقساط المستحقة',
    icon: Icons.event_note_rounded,
    palette: AppModulePalettes.reports,
    variants: [
      ReportVariantDefinition(
        id: 'main',
        label: 'الديون والأقساط',
        icon: Icons.request_quote_rounded,
        filters: _debtFilters,
        metrics: _debtMetrics,
        columns: _debtColumns,
        rows: _debtRows,
      ),
    ],
  ),
]);

const List<ReportFilterOption> _currencyOptions = [
  ReportFilterOption('all', 'الكل'),
  ReportFilterOption('IQD', 'دينار'),
  ReportFilterOption('USD', 'دولار'),
];

const List<ReportFilterOption> _warehouseOptions = [
  ReportFilterOption('all', 'الكل'),
  ReportFilterOption('main', 'الرئيسي'),
  ReportFilterOption('karrada', 'الكرادة'),
  ReportFilterOption('mansour', 'المنصور'),
  ReportFilterOption('rasafa', 'الرصافة'),
];

const List<ReportFilterOption> _invoiceStatusOptions = [
  ReportFilterOption('all', 'الكل'),
  ReportFilterOption('posted', 'مرحل'),
  ReportFilterOption('draft', 'مسودة'),
  ReportFilterOption('cancelled', 'ملغاة'),
];

const List<ReportFilterDefinition> _salesFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'الفترة'),
  ReportFilterDefinition.dropdown(
    id: 'warehouse',
    label: 'المخزن',
    icon: Icons.warehouse_rounded,
    options: _warehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'customer',
    label: 'الزبون',
    icon: Icons.person_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('dijla', 'أسواق دجلة'),
      ReportFilterOption('ahmed', 'أحمد كريم'),
      ReportFilterOption('nakheel', 'شركة النخيل للتجارة'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'saleType',
    label: 'نوع البيع',
    icon: Icons.point_of_sale_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('cash', 'نقدي'),
      ReportFilterOption('credit', 'آجل'),
      ReportFilterOption('installments', 'أقساط'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'status',
    label: 'الحالة',
    icon: Icons.task_alt_rounded,
    options: _invoiceStatusOptions,
  ),
];

const List<ReportMetricDefinition> _salesMetrics = [
  ReportMetricDefinition(label: 'عدد القوائم - دينار', value: '2'),
  ReportMetricDefinition(label: 'الإجمالي - دينار', value: '487,000'),
  ReportMetricDefinition(label: 'المقبوض - دينار', value: '310,000'),
  ReportMetricDefinition(label: 'المتبقي - دينار', value: '177,000'),
  ReportMetricDefinition(label: 'عدد القوائم - دولار', value: '1'),
  ReportMetricDefinition(label: 'الإجمالي - دولار', value: '1,250.00'),
  ReportMetricDefinition(label: 'المقبوض - دولار', value: '250.00'),
  ReportMetricDefinition(label: 'المتبقي - دولار', value: '1,000.00'),
];

const List<ReportColumnDefinition> _salesColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم القائمة', numeric: true),
  ReportColumnDefinition(label: 'التاريخ', numeric: true),
  ReportColumnDefinition(label: 'الزبون', flex: 1.4),
  ReportColumnDefinition(label: 'المخزن'),
  ReportColumnDefinition(label: 'نوع البيع'),
  ReportColumnDefinition(label: 'العملة'),
  ReportColumnDefinition(label: 'الإجمالي', numeric: true),
  ReportColumnDefinition(label: 'المقبوض', numeric: true),
  ReportColumnDefinition(label: 'المتبقي', numeric: true),
  ReportColumnDefinition(label: 'الحالة'),
  ReportColumnDefinition(label: 'عدد المواد', numeric: true),
];

final List<ReportRowDefinition> _salesRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'sales-103',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'customer': 'dijla',
      'saleType': 'cash',
      'currency': 'IQD',
      'status': 'posted',
    },
    cells: const [
      '1',
      '103',
      '2026/07/27',
      'أسواق دجلة',
      'الرئيسي',
      'نقدي',
      'دينار',
      '310,000',
      '310,000',
      '0',
      'مرحل',
      '3',
    ],
  ),
  ReportRowDefinition(
    id: 'sales-102',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'warehouse': 'mansour',
      'customer': 'ahmed',
      'saleType': 'installments',
      'currency': 'USD',
      'status': 'posted',
    },
    cells: const [
      '2',
      '102',
      '2026/07/26',
      'أحمد كريم',
      'المنصور',
      'أقساط',
      'دولار',
      '1,250.00',
      '250.00',
      '1,000.00',
      'مرحل',
      '2',
    ],
  ),
  ReportRowDefinition(
    id: 'sales-101',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'warehouse': 'rasafa',
      'customer': 'nakheel',
      'saleType': 'credit',
      'currency': 'IQD',
      'status': 'posted',
    },
    cells: const [
      '3',
      '101',
      '2026/07/25',
      'شركة النخيل للتجارة',
      'الرصافة',
      'آجل',
      'دينار',
      '177,000',
      '0',
      '177,000',
      'مرحل',
      '3',
    ],
  ),
]);

const List<ReportFilterDefinition> _purchaseFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'الفترة'),
  ReportFilterDefinition.dropdown(
    id: 'warehouse',
    label: 'المخزن',
    icon: Icons.warehouse_rounded,
    options: _warehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'supplier',
    label: 'المجهز',
    icon: Icons.local_shipping_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('karrada', 'مجهز الكرادة'),
      ReportFilterOption('global', 'شركة التجارة العالمية'),
      ReportFilterOption('rafidain', 'شركة الرافدين للتجهيز'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'purchaseType',
    label: 'نوع الشراء',
    icon: Icons.shopping_cart_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('local', 'محلي'),
      ReportFilterOption('import', 'إستيراد'),
      ReportFilterOption('return', 'إرجاع'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'paymentType',
    label: 'نوع الدفع',
    icon: Icons.payments_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('cash', 'نقدي'),
      ReportFilterOption('credit', 'آجل'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'status',
    label: 'الحالة',
    icon: Icons.task_alt_rounded,
    options: _invoiceStatusOptions,
  ),
];

const List<ReportMetricDefinition> _purchaseMetrics = [
  ReportMetricDefinition(label: 'عدد القوائم - دينار', value: '2'),
  ReportMetricDefinition(label: 'الإجمالي - دينار', value: '240,000'),
  ReportMetricDefinition(label: 'المدفوع - دينار', value: '90,000'),
  ReportMetricDefinition(label: 'المتبقي - دينار', value: '150,000'),
  ReportMetricDefinition(label: 'عدد القوائم - دولار', value: '1'),
  ReportMetricDefinition(label: 'الإجمالي - دولار', value: '1,500.00'),
  ReportMetricDefinition(label: 'المدفوع - دولار', value: '500.00'),
  ReportMetricDefinition(label: 'المتبقي - دولار', value: '1,000.00'),
];

const List<ReportColumnDefinition> _purchaseColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم القائمة', numeric: true),
  ReportColumnDefinition(label: 'التاريخ', numeric: true),
  ReportColumnDefinition(label: 'المجهز', flex: 1.5),
  ReportColumnDefinition(label: 'المخزن'),
  ReportColumnDefinition(label: 'نوع الشراء'),
  ReportColumnDefinition(label: 'نوع الدفع'),
  ReportColumnDefinition(label: 'العملة'),
  ReportColumnDefinition(label: 'الإجمالي', numeric: true),
  ReportColumnDefinition(label: 'المدفوع', numeric: true),
  ReportColumnDefinition(label: 'المتبقي', numeric: true),
  ReportColumnDefinition(label: 'الحالة'),
  ReportColumnDefinition(label: 'عدد المواد', numeric: true),
];

final List<ReportRowDefinition> _purchaseRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'purchases-103',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'supplier': 'karrada',
      'purchaseType': 'return',
      'paymentType': 'cash',
      'currency': 'IQD',
      'status': 'posted',
    },
    cells: const [
      '1',
      '103',
      '2026/07/27',
      'مجهز الكرادة',
      'الرئيسي',
      'إرجاع',
      'نقدي',
      'دينار',
      '90,000',
      '90,000',
      '0',
      'مرحل',
      '1',
    ],
  ),
  ReportRowDefinition(
    id: 'purchases-102',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'warehouse': 'mansour',
      'supplier': 'global',
      'purchaseType': 'import',
      'paymentType': 'credit',
      'currency': 'USD',
      'status': 'posted',
    },
    cells: const [
      '2',
      '102',
      '2026/07/26',
      'شركة التجارة العالمية',
      'المنصور',
      'إستيراد',
      'آجل',
      'دولار',
      '1,500.00',
      '500.00',
      '1,000.00',
      'مرحل',
      '2',
    ],
  ),
  ReportRowDefinition(
    id: 'purchases-101',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'warehouse': 'rasafa',
      'supplier': 'rafidain',
      'purchaseType': 'local',
      'paymentType': 'credit',
      'currency': 'IQD',
      'status': 'posted',
    },
    cells: const [
      '3',
      '101',
      '2026/07/25',
      'شركة الرافدين للتجهيز',
      'الرصافة',
      'محلي',
      'آجل',
      'دينار',
      '150,000',
      '0',
      '150,000',
      'مرحل',
      '2',
    ],
  ),
]);

const List<ReportFilterDefinition> _profitFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'الفترة'),
  ReportFilterDefinition.dropdown(
    id: 'warehouse',
    label: 'المخزن',
    icon: Icons.warehouse_rounded,
    options: _warehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'customer',
    label: 'الزبون',
    icon: Icons.person_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('dijla', 'أسواق دجلة'),
      ReportFilterOption('ahmed', 'أحمد كريم'),
      ReportFilterOption('nakheel', 'شركة النخيل للتجارة'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'product',
    label: 'المادة',
    icon: Icons.inventory_2_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('notebook', 'دفتر ملاحظات'),
      ReportFilterOption('bluePen', 'قلم أزرق'),
      ReportFilterOption('calculator', 'حاسبة مكتبية'),
      ReportFilterOption('thermalPrinter', 'طابعة حرارية'),
      ReportFilterOption('barcodeScanner', 'ماسح باركود'),
      ReportFilterOption('printingPaper', 'ورق طباعة'),
      ReportFilterOption('printerInk', 'حبر طابعة'),
      ReportFilterOption('stapler', 'دباسة'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
];

const List<ReportMetricDefinition> _profitMetrics = [
  ReportMetricDefinition(label: 'المبيعات المحتسبة - دينار', value: '190,000'),
  ReportMetricDefinition(label: 'التكلفة - دينار', value: '120,000'),
  ReportMetricDefinition(label: 'الربح - دينار', value: '70,000'),
  ReportMetricDefinition(label: 'هامش الربح - دينار', value: '36.84%'),
  ReportMetricDefinition(label: 'المبيعات المحتسبة - دولار', value: '850.00'),
  ReportMetricDefinition(label: 'التكلفة - دولار', value: '600.00'),
  ReportMetricDefinition(label: 'الربح - دولار', value: '250.00'),
  ReportMetricDefinition(label: 'هامش الربح - دولار', value: '29.41%'),
];

const List<ReportColumnDefinition> _profitColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم القائمة', numeric: true),
  ReportColumnDefinition(label: 'التاريخ', numeric: true),
  ReportColumnDefinition(label: 'الزبون', flex: 1.4),
  ReportColumnDefinition(label: 'المخزن'),
  ReportColumnDefinition(label: 'رمز المادة', numeric: true),
  ReportColumnDefinition(label: 'اسم المادة', flex: 1.4),
  ReportColumnDefinition(label: 'الكمية', numeric: true),
  ReportColumnDefinition(label: 'سعر البيع', numeric: true),
  ReportColumnDefinition(label: 'إجمالي البيع', numeric: true),
  ReportColumnDefinition(label: 'إجمالي التكلفة', numeric: true),
  ReportColumnDefinition(label: 'الربح', numeric: true),
  ReportColumnDefinition(label: 'نسبة الربح', numeric: true),
  ReportColumnDefinition(label: 'حالة التكلفة'),
  ReportColumnDefinition(label: 'طريقة التكلفة'),
  ReportColumnDefinition(label: 'العملة'),
];

final List<ReportRowDefinition> _profitRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'profits-103-1001',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'customer': 'dijla',
      'product': 'notebook',
      'currency': 'IQD',
    },
    cells: const [
      '1',
      '103',
      '2026/07/27',
      'أسواق دجلة',
      'الرئيسي',
      '1001',
      'دفتر ملاحظات',
      '4',
      '35,000',
      '140,000',
      '100,000',
      '40,000',
      '28.57%',
      'متوفرة',
      'متوسط متحرك',
      'دينار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-103-1002',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'customer': 'dijla',
      'product': 'bluePen',
      'currency': 'IQD',
    },
    cells: const [
      '2',
      '103',
      '2026/07/27',
      'أسواق دجلة',
      'الرئيسي',
      '1002',
      'قلم أزرق',
      '10',
      '5,000',
      '50,000',
      '20,000',
      '30,000',
      '60%',
      'متوفرة',
      'متوسط متحرك',
      'دينار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-103-1003',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'karrada',
      'customer': 'dijla',
      'product': 'calculator',
      'currency': 'IQD',
    },
    cells: const [
      '3',
      '103',
      '2026/07/27',
      'أسواق دجلة',
      'الكرادة',
      '1003',
      'حاسبة مكتبية',
      '1',
      '125,000',
      '125,000',
      '-',
      '-',
      '-',
      'غير متوفرة',
      '-',
      'دينار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-102-2001',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'warehouse': 'mansour',
      'customer': 'ahmed',
      'product': 'thermalPrinter',
      'currency': 'USD',
    },
    cells: const [
      '4',
      '102',
      '2026/07/26',
      'أحمد كريم',
      'المنصور',
      '2001',
      'طابعة حرارية',
      '1',
      '850.00',
      '850.00',
      '600.00',
      '250.00',
      '29.41%',
      'متوفرة',
      'متوسط متحرك',
      'دولار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-102-2002',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'warehouse': 'mansour',
      'customer': 'ahmed',
      'product': 'barcodeScanner',
      'currency': 'USD',
    },
    cells: const [
      '5',
      '102',
      '2026/07/26',
      'أحمد كريم',
      'المنصور',
      '2002',
      'ماسح باركود',
      '2',
      '200.00',
      '400.00',
      '-',
      '-',
      '-',
      'غير متوفرة',
      '-',
      'دولار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-101-3001',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'warehouse': 'rasafa',
      'customer': 'nakheel',
      'product': 'printingPaper',
      'currency': 'IQD',
    },
    cells: const [
      '6',
      '101',
      '2026/07/25',
      'شركة النخيل للتجارة',
      'الرصافة',
      '3001',
      'ورق طباعة',
      '5',
      '12,000',
      '60,000',
      '-',
      '-',
      '-',
      'غير متوفرة',
      '-',
      'دينار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-101-3002',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'warehouse': 'rasafa',
      'customer': 'nakheel',
      'product': 'printerInk',
      'currency': 'IQD',
    },
    cells: const [
      '7',
      '101',
      '2026/07/25',
      'شركة النخيل للتجارة',
      'الرصافة',
      '3002',
      'حبر طابعة',
      '2',
      '45,000',
      '90,000',
      '-',
      '-',
      '-',
      'غير متوفرة',
      '-',
      'دينار',
    ],
  ),
  ReportRowDefinition(
    id: 'profits-101-3003',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'warehouse': 'main',
      'customer': 'nakheel',
      'product': 'stapler',
      'currency': 'IQD',
    },
    cells: const [
      '8',
      '101',
      '2026/07/25',
      'شركة النخيل للتجارة',
      'الرئيسي',
      '3003',
      'دباسة',
      '3',
      '9,000',
      '27,000',
      '-',
      '-',
      '-',
      'غير متوفرة',
      '-',
      'دينار',
    ],
  ),
]);

const List<ReportFilterOption> _inventoryWarehouseOptions = [
  ReportFilterOption('all', 'الكل'),
  ReportFilterOption('main', 'المخزن الرئيسي'),
  ReportFilterOption('karrada', 'مخزن الكرادة'),
  ReportFilterOption('basra', 'مخزن البصرة'),
  ReportFilterOption('erbil', 'مخزن أربيل'),
];

const List<ReportFilterDefinition> _currentStockFilters = [
  ReportFilterDefinition.dropdown(
    id: 'warehouse',
    label: 'المخزن',
    icon: Icons.warehouse_rounded,
    options: _inventoryWarehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'product',
    label: 'المادة',
    icon: Icons.inventory_2_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('p1001', 'P-1001 - طابعة ليزر'),
      ReportFilterOption('p1002', 'P-1002 - حبر طابعة أسود'),
      ReportFilterOption('p1003', 'P-1003 - ورق تصوير A4'),
      ReportFilterOption('p1004', 'P-1004 - آلة حاسبة مكتبية'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'group',
    label: 'المجموعة',
    icon: Icons.category_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('officeDevices', 'أجهزة مكتبية'),
      ReportFilterOption('printingSupplies', 'مستلزمات طباعة'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'type',
    label: 'النوع',
    icon: Icons.sell_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('printers', 'طابعات'),
      ReportFilterOption('inks', 'أحبار'),
      ReportFilterOption('printingPaper', 'ورق طباعة'),
      ReportFilterOption('calculators', 'آلات حاسبة'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'stockState',
    label: 'حالة المخزون',
    icon: Icons.inventory_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('available', 'متوفر'),
      ReportFilterOption('out', 'نافد'),
    ],
  ),
];

const List<ReportMetricDefinition> _currentStockMetrics = [
  ReportMetricDefinition(label: 'المواد المختلفة', value: '4'),
  ReportMetricDefinition(label: 'المخازن', value: '4'),
  ReportMetricDefinition(label: 'الأرصدة الموجبة', value: '9'),
  ReportMetricDefinition(label: 'مجموع الكميات', value: '344'),
];

const List<ReportColumnDefinition> _currentStockColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رمز المادة', numeric: true),
  ReportColumnDefinition(label: 'اسم المادة', flex: 1.5),
  ReportColumnDefinition(label: 'المجموعة', flex: 1.3),
  ReportColumnDefinition(label: 'النوع'),
  ReportColumnDefinition(label: 'المخزن', flex: 1.3),
  ReportColumnDefinition(label: 'الكمية', numeric: true),
];

final List<ReportRowDefinition> _currentStockRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'stock-p1001-main',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'product': 'p1001',
      'group': 'officeDevices',
      'type': 'printers',
      'stockState': 'available',
    },
    cells: const [
      '1',
      'P-1001',
      'طابعة ليزر',
      'أجهزة مكتبية',
      'طابعات',
      'المخزن الرئيسي',
      '18',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1002-main',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'product': 'p1002',
      'group': 'printingSupplies',
      'type': 'inks',
      'stockState': 'available',
    },
    cells: const [
      '2',
      'P-1002',
      'حبر طابعة أسود',
      'مستلزمات طباعة',
      'أحبار',
      'المخزن الرئيسي',
      '64',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1003-main',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'product': 'p1003',
      'group': 'printingSupplies',
      'type': 'printingPaper',
      'stockState': 'available',
    },
    cells: const [
      '3',
      'P-1003',
      'ورق تصوير A4',
      'مستلزمات طباعة',
      'ورق طباعة',
      'المخزن الرئيسي',
      '120',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1004-main',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'main',
      'product': 'p1004',
      'group': 'officeDevices',
      'type': 'calculators',
      'stockState': 'available',
    },
    cells: const [
      '4',
      'P-1004',
      'آلة حاسبة مكتبية',
      'أجهزة مكتبية',
      'آلات حاسبة',
      'المخزن الرئيسي',
      '25',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1001-karrada',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'karrada',
      'product': 'p1001',
      'group': 'officeDevices',
      'type': 'printers',
      'stockState': 'available',
    },
    cells: const [
      '5',
      'P-1001',
      'طابعة ليزر',
      'أجهزة مكتبية',
      'طابعات',
      'مخزن الكرادة',
      '7',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1003-karrada',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'karrada',
      'product': 'p1003',
      'group': 'printingSupplies',
      'type': 'printingPaper',
      'stockState': 'available',
    },
    cells: const [
      '6',
      'P-1003',
      'ورق تصوير A4',
      'مستلزمات طباعة',
      'ورق طباعة',
      'مخزن الكرادة',
      '45',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1002-basra',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'basra',
      'product': 'p1002',
      'group': 'printingSupplies',
      'type': 'inks',
      'stockState': 'available',
    },
    cells: const [
      '7',
      'P-1002',
      'حبر طابعة أسود',
      'مستلزمات طباعة',
      'أحبار',
      'مخزن البصرة',
      '22',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1004-basra',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'basra',
      'product': 'p1004',
      'group': 'officeDevices',
      'type': 'calculators',
      'stockState': 'available',
    },
    cells: const [
      '8',
      'P-1004',
      'آلة حاسبة مكتبية',
      'أجهزة مكتبية',
      'آلات حاسبة',
      'مخزن البصرة',
      '11',
    ],
  ),
  ReportRowDefinition(
    id: 'stock-p1003-erbil',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'warehouse': 'erbil',
      'product': 'p1003',
      'group': 'printingSupplies',
      'type': 'printingPaper',
      'stockState': 'available',
    },
    cells: const [
      '9',
      'P-1003',
      'ورق تصوير A4',
      'مستلزمات طباعة',
      'ورق طباعة',
      'مخزن أربيل',
      '32',
    ],
  ),
]);

const List<ReportFilterDefinition> _transferFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'الفترة'),
  ReportFilterDefinition.dropdown(
    id: 'sourceWarehouse',
    label: 'من مخزن',
    icon: Icons.warehouse_outlined,
    options: _inventoryWarehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'destinationWarehouse',
    label: 'إلى مخزن',
    icon: Icons.warehouse_rounded,
    options: _inventoryWarehouseOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'product',
    label: 'المادة',
    icon: Icons.inventory_2_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('paperA4', 'ورق تصوير A4'),
      ReportFilterOption('blackInk', 'حبر طابعة أسود'),
      ReportFilterOption('calculator', 'آلة حاسبة مكتبية'),
    ],
  ),
];

const List<ReportMetricDefinition> _transferMetrics = [
  ReportMetricDefinition(label: 'عدد عمليات النقل', value: '2'),
  ReportMetricDefinition(label: 'عدد سطور المواد', value: '3'),
  ReportMetricDefinition(label: 'مجموع الكميات', value: '27'),
];

const List<ReportColumnDefinition> _transferColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم النقل', numeric: true),
  ReportColumnDefinition(label: 'التاريخ', numeric: true),
  ReportColumnDefinition(label: 'من مخزن', flex: 1.3),
  ReportColumnDefinition(label: 'إلى مخزن', flex: 1.3),
  ReportColumnDefinition(label: 'المواد', flex: 3),
];

final List<ReportRowDefinition> _transferRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'transfer-104',
    date: DateTime(2026, 7, 24),
    filterValues: const {
      'sourceWarehouse': 'main',
      'destinationWarehouse': 'karrada',
      'product': 'paperA4',
    },
    cells: const [
      '1',
      '104',
      '2026/07/24',
      'المخزن الرئيسي',
      'مخزن الكرادة',
      'P-1003 - ورق تصوير A4 (20)',
    ],
  ),
  ReportRowDefinition(
    id: 'transfer-103',
    date: DateTime(2026, 7, 22),
    filterValues: const {
      'sourceWarehouse': 'basra',
      'destinationWarehouse': 'main',
      'product': 'blackInk|calculator',
    },
    searchTerms: const ['آلة حاسبة مكتبية', 'P-1004'],
    cells: const [
      '2',
      '103',
      '2026/07/22',
      'مخزن البصرة',
      'المخزن الرئيسي',
      'P-1002 - حبر طابعة أسود (5)، P-1004 - آلة حاسبة مكتبية (2)',
    ],
  ),
]);

const List<ReportFilterDefinition> _cashboxFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'الفترة'),
  ReportFilterDefinition.dropdown(
    id: 'transactionType',
    label: 'نوع الحركة',
    icon: Icons.swap_vert_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('in', 'قبض'),
      ReportFilterOption('out', 'صرف'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'mainAccount',
    label: 'الحساب الرئيسي',
    icon: Icons.account_balance_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('parties', 'الأطراف'),
      ReportFilterOption('expenses', 'المصاريف'),
      ReportFilterOption('otherIncome', 'إيرادات أخرى'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'subAccount',
    label: 'الحساب الفرعي',
    icon: Icons.account_tree_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('nakheel', '1 - شركة النخيل'),
      ReportFilterOption('transport', 'نقل'),
      ReportFilterOption('rafidain', '3 - مجهز الرافدين'),
      ReportFilterOption('services', 'خدمات'),
      ReportFilterOption('maintenance', 'صيانة'),
      ReportFilterOption('ahmed', '2 - أحمد كريم'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
];

const List<ReportMetricDefinition> _cashboxMetrics = [
  ReportMetricDefinition(label: 'القبض - دينار', value: '1,525,000'),
  ReportMetricDefinition(label: 'الصرف - دينار', value: '210,000'),
  ReportMetricDefinition(label: 'الصافي - دينار', value: '1,315,000'),
  ReportMetricDefinition(label: 'الرصيد - دينار', value: '11,115,000'),
  ReportMetricDefinition(label: 'القبض - دولار', value: '0'),
  ReportMetricDefinition(label: 'الصرف - دولار', value: '400.00'),
  ReportMetricDefinition(label: 'الصافي - دولار', value: '-400.00'),
  ReportMetricDefinition(label: 'الرصيد - دولار', value: '4,100.00'),
  ReportMetricDefinition(label: 'عدد الحركات', value: '6'),
];

const List<ReportColumnDefinition> _cashboxColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم السند', numeric: true),
  ReportColumnDefinition(label: 'التاريخ', numeric: true),
  ReportColumnDefinition(label: 'الوقت', numeric: true),
  ReportColumnDefinition(label: 'نوع الحركة'),
  ReportColumnDefinition(label: 'الحساب الرئيسي'),
  ReportColumnDefinition(label: 'الحساب الفرعي', flex: 1.5),
  ReportColumnDefinition(label: 'مبلغ دينار', numeric: true),
  ReportColumnDefinition(label: 'مبلغ دولار', numeric: true),
  ReportColumnDefinition(label: 'سعر الصرف', numeric: true),
  ReportColumnDefinition(label: 'الملاحظات', flex: 1.5),
];

final List<ReportRowDefinition> _cashboxRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'cashbox-1',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'transactionType': 'in',
      'mainAccount': 'parties',
      'subAccount': 'nakheel',
      'currency': 'IQD',
    },
    cells: const [
      '1',
      '1',
      '2026/07/27',
      '08:30 ص',
      'قبض',
      'الأطراف',
      '1 - شركة النخيل',
      '750,000',
      '0',
      '1,310',
      'دفعة على الحساب',
    ],
  ),
  ReportRowDefinition(
    id: 'cashbox-2',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'transactionType': 'out',
      'mainAccount': 'expenses',
      'subAccount': 'transport',
      'currency': 'IQD',
    },
    cells: const [
      '2',
      '2',
      '2026/07/27',
      '09:10 ص',
      'صرف',
      'المصاريف',
      'نقل',
      '125,000',
      '0',
      '1,310',
      'نقل مواد',
    ],
  ),
  ReportRowDefinition(
    id: 'cashbox-3',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'transactionType': 'out',
      'mainAccount': 'parties',
      'subAccount': 'rafidain',
      'currency': 'USD',
    },
    cells: const [
      '3',
      '3',
      '2026/07/27',
      '10:05 ص',
      'صرف',
      'الأطراف',
      '3 - مجهز الرافدين',
      '0',
      '400.00',
      '1,310',
      'تسديد جزء',
    ],
  ),
  ReportRowDefinition(
    id: 'cashbox-4',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'transactionType': 'in',
      'mainAccount': 'otherIncome',
      'subAccount': 'services',
      'currency': 'IQD',
    },
    cells: const [
      '4',
      '4',
      '2026/07/26',
      '11:40 ص',
      'قبض',
      'إيرادات أخرى',
      'خدمات',
      '300,000',
      '0',
      '1,310',
      '-',
    ],
  ),
  ReportRowDefinition(
    id: 'cashbox-5',
    date: DateTime(2026, 7, 25),
    filterValues: const {
      'transactionType': 'out',
      'mainAccount': 'expenses',
      'subAccount': 'maintenance',
      'currency': 'IQD',
    },
    cells: const [
      '5',
      '5',
      '2026/07/25',
      '01:15 م',
      'صرف',
      'المصاريف',
      'صيانة',
      '85,000',
      '0',
      '1,310',
      'صيانة أجهزة المكتب',
    ],
  ),
  ReportRowDefinition(
    id: 'cashbox-6',
    date: DateTime(2026, 7, 24),
    filterValues: const {
      'transactionType': 'in',
      'mainAccount': 'parties',
      'subAccount': 'ahmed',
      'currency': 'IQD',
    },
    cells: const [
      '6',
      '6',
      '2026/07/24',
      '03:20 م',
      'قبض',
      'الأطراف',
      '2 - أحمد كريم',
      '475,000',
      '0',
      '1,310',
      'تسديد كامل الرصيد',
    ],
  ),
]);

const List<ReportFilterDefinition> _partyBalanceFilters = [
  ReportFilterDefinition.dropdown(
    id: 'partyType',
    label: 'نوع الطرف',
    icon: Icons.groups_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('customer', 'زبون'),
      ReportFilterOption('supplier', 'مجهز'),
      ReportFilterOption('both', 'زبون ومجهز'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'direction',
    label: 'اتجاه الرصيد',
    icon: Icons.compare_arrows_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('receivable', 'لنا'),
      ReportFilterOption('payable', 'علينا'),
      ReportFilterOption('zero', 'صفر'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'workEntity',
    label: 'جهة العمل',
    icon: Icons.business_center_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('general', 'التجارة العامة'),
      ReportFilterOption('retail', 'تجارة المفرد'),
      ReportFilterOption('supplies', 'تجهيز المواد'),
      ReportFilterOption('wholesale', 'تجارة الجملة'),
      ReportFilterOption('officeDevices', 'الأجهزة المكتبية'),
      ReportFilterOption('services', 'الخدمات'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'branch',
    label: 'الفرع',
    icon: Icons.account_tree_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('baghdad', 'بغداد'),
      ReportFilterOption('mansour', 'المنصور'),
      ReportFilterOption('basra', 'البصرة'),
      ReportFilterOption('najaf', 'النجف'),
      ReportFilterOption('mosul', 'الموصل'),
      ReportFilterOption('kadhimiya', 'الكاظمية'),
      ReportFilterOption('karbala', 'كربلاء'),
    ],
  ),
];

const List<ReportMetricDefinition> _partyBalanceMetrics = [
  ReportMetricDefinition(label: 'عدد الأطراف', value: '8'),
  ReportMetricDefinition(label: 'بدون رصيد', value: '0'),
  ReportMetricDefinition(label: 'ذمم لنا - دينار', value: '2,775,000'),
  ReportMetricDefinition(label: 'ذمم لنا - دولار', value: '1,375.00'),
  ReportMetricDefinition(label: 'ذمم علينا - دينار', value: '5,875,000'),
  ReportMetricDefinition(label: 'ذمم علينا - دولار', value: '1,625.00'),
];

const List<ReportColumnDefinition> _partyBalanceColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'رقم الطرف', numeric: true),
  ReportColumnDefinition(label: 'اسم الطرف', flex: 1.5),
  ReportColumnDefinition(label: 'نوع الطرف'),
  ReportColumnDefinition(label: 'جهة العمل', flex: 1.3),
  ReportColumnDefinition(label: 'الفرع'),
  ReportColumnDefinition(label: 'الهاتف', numeric: true),
  ReportColumnDefinition(label: 'المدينة'),
  ReportColumnDefinition(label: 'رصيد الدينار', numeric: true),
  ReportColumnDefinition(label: 'اتجاهه'),
  ReportColumnDefinition(label: 'رصيد الدولار', numeric: true),
  ReportColumnDefinition(label: 'اتجاهه'),
];

final List<ReportRowDefinition> _partyBalanceRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'party-1',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'both',
      'direction': 'receivable',
      'currency': 'IQD|USD',
      'workEntity': 'general',
      'branch': 'baghdad',
    },
    cells: const [
      '1',
      '1',
      'شركة النخيل للتجارة',
      'زبون ومجهز',
      'التجارة العامة',
      'بغداد',
      '07701234567',
      'بغداد',
      '1,250,000',
      'لنا',
      '850.00',
      'لنا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-2',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'customer',
      'direction': 'receivable',
      'currency': 'IQD',
      'workEntity': 'retail',
      'branch': 'mansour',
    },
    cells: const [
      '2',
      '2',
      'أحمد كريم',
      'زبون',
      'تجارة المفرد',
      'المنصور',
      '07801112233',
      'بغداد',
      '475,000',
      'لنا',
      '0',
      'صفر',
    ],
  ),
  ReportRowDefinition(
    id: 'party-3',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'supplier',
      'direction': 'payable',
      'currency': 'IQD|USD',
      'workEntity': 'supplies',
      'branch': 'basra',
    },
    cells: const [
      '3',
      '3',
      'مجهز الرافدين',
      'مجهز',
      'تجهيز المواد',
      'البصرة',
      '07709998877',
      'البصرة',
      '3,200,000',
      'علينا',
      '1,200.00',
      'علينا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-5',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'customer',
      'direction': 'receivable',
      'currency': 'IQD|USD',
      'workEntity': 'wholesale',
      'branch': 'najaf',
    },
    cells: const [
      '4',
      '5',
      'أسواق دجلة',
      'زبون',
      'تجارة الجملة',
      'النجف',
      '07601110000',
      'النجف',
      '840,000',
      'لنا',
      '300.00',
      'لنا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-6',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'supplier',
      'direction': 'payable',
      'currency': 'IQD|USD',
      'workEntity': 'officeDevices',
      'branch': 'mosul',
    },
    cells: const [
      '5',
      '6',
      'شركة الموصل الحديثة',
      'مجهز',
      'الأجهزة المكتبية',
      'الموصل',
      '07705554433',
      'الموصل',
      '950,000',
      'علينا',
      '425.00',
      'علينا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-7',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'customer',
      'direction': 'receivable',
      'currency': 'IQD|USD',
      'workEntity': 'services',
      'branch': 'basra',
    },
    cells: const [
      '6',
      '7',
      'مكتب البصرة',
      'زبون',
      'الخدمات',
      'البصرة',
      '07805556677',
      'البصرة',
      '210,000',
      'لنا',
      '75.00',
      'لنا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-8',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'customer',
      'direction': 'receivable',
      'currency': 'USD',
      'workEntity': 'retail',
      'branch': 'kadhimiya',
    },
    cells: const [
      '7',
      '8',
      'علي حسن',
      'زبون',
      'تجارة المفرد',
      'الكاظمية',
      '07701110022',
      'بغداد',
      '0',
      'صفر',
      '150.00',
      'لنا',
    ],
  ),
  ReportRowDefinition(
    id: 'party-9',
    date: DateTime(2026, 7, 27),
    filterValues: const {
      'partyType': 'supplier',
      'direction': 'payable',
      'currency': 'IQD',
      'workEntity': 'supplies',
      'branch': 'karbala',
    },
    cells: const [
      '8',
      '9',
      'مجهز الفرات',
      'مجهز',
      'تجهيز المواد',
      'كربلاء',
      '07604443322',
      'كربلاء',
      '1,725,000',
      'علينا',
      '0',
      'صفر',
    ],
  ),
]);

const List<ReportFilterDefinition> _debtFilters = [
  ReportFilterDefinition.dateRange(id: 'period', label: 'فترة الاستحقاق'),
  ReportFilterDefinition.dropdown(
    id: 'customer',
    label: 'الزبون',
    icon: Icons.person_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('nakheel', 'شركة النخيل للتجارة'),
      ReportFilterOption('ahmed', 'أحمد كريم'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'recordType',
    label: 'نوع السجل',
    icon: Icons.description_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('debt', 'دين'),
      ReportFilterOption('installment', 'قسط'),
    ],
  ),
  ReportFilterDefinition.dropdown(
    id: 'currency',
    label: 'العملة',
    icon: Icons.currency_exchange_rounded,
    options: _currencyOptions,
  ),
  ReportFilterDefinition.dropdown(
    id: 'status',
    label: 'الحالة',
    icon: Icons.schedule_rounded,
    options: [
      ReportFilterOption('all', 'الكل'),
      ReportFilterOption('due', 'مستحق'),
      ReportFilterOption('overdue', 'متأخر'),
      ReportFilterOption('paid', 'مدفوع'),
    ],
  ),
];

const List<ReportMetricDefinition> _debtMetrics = [
  ReportMetricDefinition(label: 'المتبقي - دينار', value: '177,000'),
  ReportMetricDefinition(label: 'المتأخر - دينار', value: '177,000'),
  ReportMetricDefinition(label: 'المستحق - دينار', value: '0'),
  ReportMetricDefinition(label: 'المدفوع - دينار', value: '0'),
  ReportMetricDefinition(label: 'المتبقي - دولار', value: '1,000.00'),
  ReportMetricDefinition(label: 'المتأخر - دولار', value: '0'),
  ReportMetricDefinition(label: 'المستحق - دولار', value: '1,000.00'),
  ReportMetricDefinition(label: 'المدفوع - دولار', value: '250.00'),
  ReportMetricDefinition(label: 'عدد المتأخر', value: '1'),
  ReportMetricDefinition(label: 'عدد المستحق', value: '2'),
];

const List<ReportColumnDefinition> _debtColumns = [
  ReportColumnDefinition(label: 'ت', numeric: true, flex: 0.5),
  ReportColumnDefinition(label: 'نوع السجل'),
  ReportColumnDefinition(label: 'رقم القائمة', numeric: true),
  ReportColumnDefinition(label: 'رقم القسط', numeric: true),
  ReportColumnDefinition(label: 'الزبون', flex: 1.5),
  ReportColumnDefinition(label: 'تاريخ الاستحقاق', numeric: true),
  ReportColumnDefinition(label: 'العملة'),
  ReportColumnDefinition(label: 'المبلغ الأصلي', numeric: true),
  ReportColumnDefinition(label: 'المدفوع', numeric: true),
  ReportColumnDefinition(label: 'المتبقي', numeric: true),
  ReportColumnDefinition(label: 'الحالة'),
  ReportColumnDefinition(label: 'الملاحظات', flex: 1.4),
];

final List<ReportRowDefinition> _debtRows =
    List<ReportRowDefinition>.unmodifiable([
  ReportRowDefinition(
    id: 'debt-101',
    date: DateTime(2026, 7, 28),
    filterValues: const {
      'customer': 'nakheel',
      'recordType': 'debt',
      'currency': 'IQD',
      'status': 'overdue',
    },
    cells: const [
      '1',
      'دين',
      '101',
      '-',
      'شركة النخيل للتجارة',
      '2026/07/28',
      'دينار',
      '177,000',
      '0',
      '177,000',
      'متأخر',
      'بيع آجل',
    ],
  ),
  ReportRowDefinition(
    id: 'installment-102-1',
    date: DateTime(2026, 7, 26),
    filterValues: const {
      'customer': 'ahmed',
      'recordType': 'installment',
      'currency': 'USD',
      'status': 'paid',
    },
    cells: const [
      '2',
      'قسط',
      '102',
      '1',
      'أحمد كريم',
      '2026/07/26',
      'دولار',
      '250.00',
      '250.00',
      '0',
      'مدفوع',
      'القسط الأول',
    ],
  ),
  ReportRowDefinition(
    id: 'installment-102-2',
    date: DateTime(2026, 8, 10),
    filterValues: const {
      'customer': 'ahmed',
      'recordType': 'installment',
      'currency': 'USD',
      'status': 'due',
    },
    cells: const [
      '3',
      'قسط',
      '102',
      '2',
      'أحمد كريم',
      '2026/08/10',
      'دولار',
      '500.00',
      '0',
      '500.00',
      'مستحق',
      '-',
    ],
  ),
  ReportRowDefinition(
    id: 'installment-102-3',
    date: DateTime(2026, 9, 10),
    filterValues: const {
      'customer': 'ahmed',
      'recordType': 'installment',
      'currency': 'USD',
      'status': 'due',
    },
    cells: const [
      '4',
      'قسط',
      '102',
      '3',
      'أحمد كريم',
      '2026/09/10',
      'دولار',
      '500.00',
      '0',
      '500.00',
      'مستحق',
      '-',
    ],
  ),
]);
